### ISSUE TITLE
build rails API and models (migrations)

### ISSUE THREAD

**Issue by dinophile** [mokutsu/bikeapp#6]

**Comment by mokutsu** [comment]
Models:
User
	-username
-email
	-avatar
	-routes join table
	-Devise columns
Routes
	-name
	-description
	-lat
	-lon
	-length
	-user_id
Waypoints
	-lat
	-long
	-route_id
Hazards
	-category
	-description
	-lat
	-long
	-street
	-active/expired
	-timestamp (last_update)
	-timestamp (created_at)
Tips
	-tip
